name: Memo
description: Memo
labels: ["document"]
assignees:
  - ee090186
body:
  - type: textarea
    id: summary
    attributes:
      label: summary
      description: Describe the memo
      value: |
        
        <br>
        <br>
    validations:
      required: true
      
  - type: textarea
    id: refelence
    attributes:
      label: Refelence
      description: Please copy and paste any refelence links
      value: |
        []()
        
        <br>
        <br>
